<?php

return [
    [
        'title' => 'Lorem ipsum dolor sit amet',
        'description' => 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. ',
        'cost' => 249,
        'discountCost' => 199,
        'new' => true,
        'img'  => '/img/img_product-1.png',
    ],
    [
        'title' => 'Lorem ipsum dolor sit amet',
        'description' => 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. ',
        'cost' => 249,
        'discountCost' => null,
        'new' => false,
        'img'  => '/img/img_product-2.png',
    ],
    [
        'title' => 'Lorem ipsum dolor sit amet',
        'description' => 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. ',
        'cost' => 125,
        'new' => true,
        'discountCost' => null,
        'img'  => '/img/img_product-3.png',
    ],
    [
        'title' => 'Lorem ipsum dolor sit amet',
        'description' => 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. ',
        'cost' => 111,
        'discountCost' => 90,
        'new' => false,
        'img'  => '/test/img/img_product-4.png',
    ],
    [
        'title' => 'test title 5',
        'description' => 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. ',
        'cost' => 249,
        'discountCost' => null,
        'new' => true,
        'img'  => '/img/img_product-5.png',
    ],
    [
        'title' => 'test title 6',
        'description' => 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. ',
        'cost' => 249,
        'discountCost' => null,
        'new' => true,
        'img'  => '/img/img_product-6.png',
    ],
    [
        'title' => 'test title 7',
        'description' => 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. ',
        'cost' => 249,
        'discountCost' => null,
        'new' => false,
        'img'  => '/img/img_product-7.png',
    ],
    [
        'title' => 'test title 8',
        'description' => 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. ',
        'cost' => 249,
        'discountCost' => null,
        'new' => false,
        'img'  => '/img/img_product-8.png',
    ],
    [
        'title' => 'test title 9',
        'description' => 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. ',
        'cost' => 249,
        'discountCost' => null,
        'new' => false,
        'img'  => '/img/img_product.png',
    ],
];